.catalog:
  name: "Zevenet LB"
  version: "v0.1.0"
  description: "Rancher External LB service powered by Zevenet loadbalancer."
  questions:
    - variable: "ZAPI_HOST"
      label: "Host Address"
      description: "IP Address and port of the Zevenet loadbalancer"
      type: "string"
      required: true
    - variable: "ZAPI_FARM"
      label: "Farm"
      description: "The name of the pre-created farm on the Zevenet loadbalancer"
      type: "string"
      required: true
    - variable: "ZAPI_KEY"
      label: "ZAPI Key"
      description: "The key of the ZAPI user"
      type: "string"
      required: true
    - variable: "LB_TARGET_RANCHER_SUFFIX"
      label: "Suffix for service names"
      description: "A suffix added to the service names"
      type: "string"
      required: true
      default: rancher
external-lb:
  health_check:
    port: 1000
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
